/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ui;

import com.controller.BookController;
import com.entity.Users;
import java.awt.Component;
import java.awt.Point;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumnModel;

@SuppressWarnings("serial")
public class MyBook extends javax.swing.JFrame {

    /**
     * Creates new form MyBook
     */
    //output logined username to frame
    //login username
    private Users user;

    public Users getUser() {
        return user;
    }

    public void setUser(Users user) {
        this.user = user;
        txtUsername.setText("Welcome " + user.getUsername());
    }

    //use default table model for the solution
    DefaultTableModel tblModel;
    BookController bookController;

    //show all books to tbltable
    public void showAllBooks() {
        bookController = new BookController();
        try {
			bookController.list(tblBook);
		} catch (Exception ex) {
			// TODO: handle exception
			Logger.getLogger(MyBook.class.getName()).log(Level.SEVERE, null, ex);
		}
    }

    //search books
    public void searchBooks() {
       try {
		String[] columns = {"books.title_id", "books.title", "publishers.pub_name", "authors.au_name", "books.notes", "books.username"};
		String columnName = columns[cboColumn.getSelectedIndex()];
		String keyword = txtKeyword.getText();
		bookController.search(columnName, keyword, tblBook);
	} catch (Exception ex) {
		// TODO: handle exception
		Logger.getLogger(MyBook.class.getName()).log(Level.SEVERE, null, ex);
		}
       if (tblModel.getRowCount() <= 0) {
    	   JOptionPane.showMessageDialog(MyBook.this, "Not found any Book");
       }
    }

    public MyBook() {
        initComponents();
        //setting table first
        tblBook.setModel(tblModel = new DefaultTableModel());
        //allow single selection mode only
        tblBook.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        //column names
        String[] columnName = {"Book ID", "Book Title", "Publishers", "Authors", "Notes", "User"};
        tblModel.setColumnIdentifiers(columnName);
        //by default, show all books
        showAllBooks();
        //when user double click on a row of table
        resizeColumnWidth(tblBook);

    }

    //resize the columns of table
    public void resizeColumnWidth(JTable table) {
        final TableColumnModel columnModel = table.getColumnModel();
        for (int column = 0; column < table.getColumnCount(); column++) {
			int width = 45;
			for (int row = 0; row < table.getRowCount(); row++) {
				TableCellRenderer renderer = table.getCellRenderer(row, column);
				Component comp = table.prepareRenderer(renderer, row, column);
				width = Math.max(comp.getPreferredSize().width + 1, width);
			}
			if (width > 150) {
				width = 150;
			}
			columnModel.getColumn(column).setPreferredWidth(width);	
		}
    }

    //return bookID of selected book
    public String getSelectedBookID() {
        int row = tblBook.getSelectedRow();
        int column = 0;
        return tblModel.getValueAt(row, column).toString();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cboPublisher = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cboColumn = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txtKeyword = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btnAddNew = new javax.swing.JButton();
        btnAddAcc = new javax.swing.JButton();
        btnAddPub = new javax.swing.JButton();
        btnEditAcc = new javax.swing.JButton();
        btnAddAu = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblBook = new javax.swing.JTable() {
        	public boolean isCellEditable(int row, int column){
                return false;
           }
        };
        txtUsername = new javax.swing.JLabel();

        cboPublisher.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search Book", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 0, 15))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jLabel1.setText("Search by");

        cboColumn.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Book ID", "Book Title", "Publisher Name", "Author Name", "Notes", "Username" }));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jLabel2.setText("Enter keyword");

        txtKeyword.setText("type here anything...");

        btnSearch.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboColumn, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtKeyword, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSearch)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cboColumn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtKeyword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnAddNew.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        btnAddNew.setText("Add New");
        btnAddNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewActionPerformed(evt);
            }
        });
        
        btnAddAcc.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        btnAddAcc.setText("Add new account");
        btnAddAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddAccActionPerformed(evt);
            }
        });
        
        btnAddPub.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        btnAddPub.setText("Add new publisher");
        btnAddPub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPubActionPerformed(evt);
            }
        });
        
        btnEditAcc.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        btnEditAcc.setText("Edit account");
        btnEditAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditAccActionPerformed(evt);
            }
        });
        
        btnAddAu.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        btnAddAu.setText("Add new author");
        btnAddAu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddAuActionPerformed(evt);
            }
        });

        tblBook.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblBook.setRowHeight(30);
        tblBook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblBookMousePressed(evt);
            }
        });
//        tblBook.addMouseListener(new java.awt.event.MouseAdapter() {
//            public void mouseExited(MouseEvent arg0) {
//            	// TODO Auto-generated method stub
//            	showAllBooks();
//            }
//        });
        jScrollPane2.setViewportView(tblBook);

        txtUsername.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        txtUsername.setText("Welcome");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane2)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnAddNew)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtUsername)
                .addGap(65, 65, 65))
            .addGroup(layout.createSequentialGroup()
                    .addComponent(btnAddAcc)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAddPub)
                    .addGap(65, 65, 65))
            .addGroup(layout.createSequentialGroup()
                    .addComponent(btnEditAcc)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAddAu)
                    .addGap(65, 65, 65))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddNew)
                    .addComponent(txtUsername))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAddAcc)
                        .addComponent(btnAddPub))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnEditAcc)
                        .addComponent(btnAddAu))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //event for Search button
    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
       searchBooks();
    }//GEN-LAST:event_btnSearchActionPerformed
    //event for AddNew button
    private void btnAddNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewActionPerformed
        // TODO add your handling code here:
        //open add new form
      AddBook addBook = new AddBook(this, true);
      addBook.setVisible(true);
    }//GEN-LAST:event_btnAddNewActionPerformed
    
    private void btnAddAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewActionPerformed
        // TODO add your handling code here:
        //open add new form
    	 if (user.getUsername().equals("sa")) {
    		 AddAcc addAcc = new AddAcc();
    		 addAcc.setVisible(true);
  	   } else {
  		   JOptionPane.showMessageDialog(MyBook.this, "Only admin (sa) can add new account!", "Alert", JOptionPane.ERROR_MESSAGE);
  	   }
    }
    private void btnAddPubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewActionPerformed
        // TODO add your handling code here:
        //open add new form
    	AddPub addPub = new AddPub();
		addPub.setVisible(true);
    }
   
    private void btnEditAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewActionPerformed
        // TODO add your handling code here:
        //open add new form
    	EditAcc editAcc = new EditAcc();
    	editAcc.setUser(user);
    	editAcc.setVisible(true);
    }
    
    private void btnAddAuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewActionPerformed
        // TODO add your handling code here:
        //open add new form
    	AddAu addAu = new AddAu();
    	addAu.setVisible(true);
    }
    //when users select a table row and double click on it, open a new form and
    //output information of selected book in detail
    private void tblBookMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBookMousePressed
        // TODO add your handling code here:
       JTable table = (JTable)evt.getSource();
       Point point = evt.getPoint();
       int row = table.rowAtPoint(point);
       //int col = table.columnAtPoint(point);
       int col = 5;
       if (evt.getClickCount() == 2 && row != -1) {
    	   
    	   if (table.getValueAt(row, col).toString().equals(user.getUsername())) {
    		   EditBook editBook = new EditBook(this, true);
        	   editBook.setVisible(true);
    	   } else {
    		   JOptionPane.showMessageDialog(MyBook.this, "Only owner user can edit this book!", "Alert", JOptionPane.ERROR_MESSAGE);
    	   }
    	   
       }
    }//GEN-LAST:event_tblBookMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddNew;
    private javax.swing.JButton btnAddAcc;
    private javax.swing.JButton btnAddPub;
    private javax.swing.JButton btnEditAcc;
    private javax.swing.JButton btnAddAu;
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox<String> cboColumn;
    private javax.swing.JComboBox<String> cboPublisher;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tblBook;
    private javax.swing.JTextField txtKeyword;
    private javax.swing.JLabel txtUsername;
    // End of variables declaration//GEN-END:variables
}
